# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 544820840699955a8fbd09b452a45ac7d6c060c5d2c2755e75b554e72cf41f31d5c81079ea69b437549872a00a5c9025362a410ad1840b56705a28e1b8ccac77

test:
  secret_key_base: a2361d14a9f6957ffc8632adcfa5aa3399911ed070f5295ecfad50f84a110a3bc64cc48df61df73711c8da3dcf9072a1b58bed87301aeff415c25d2cf7ef0745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
